[package]
name = "ferris_grep"
version = "1.0.0"
authors = ["Ogbu Nnamdi <ogbunnamdi@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = "3"
owo-colors = "3.5.0"